import { EventTemplate } from "../types";

export const EVENT_TEMPLATES: EventTemplate[] = [
  {
    id: "drug-rumor-leak",
    title: "Drug Trial Rumor Leaks",
    description: "Unverified efficacy chatter spikes pharma volatility.",
    visibility: "questionable",
    affectedSectors: ["pharma"],
    direction: 0.8,
    magnitude: 0.85,
    confidence: 0.35,
    heatImpact: 4,
    tags: ["rumor", "pharma"],
    macroWeights: { "AI Hype": 1.2, "Risk-Off": 0.8 }
  },
  {
    id: "grid-outage",
    title: "Grid Outage Triggers Energy Spike",
    description: "Energy operators bid up spot exposure amid outage concerns.",
    visibility: "public",
    affectedSectors: ["energy"],
    direction: 0.7,
    magnitude: 0.7,
    confidence: 0.75,
    tags: ["energy", "commodity"],
    macroWeights: { "Inflation Scare": 1.3 }
  },
  {
    id: "consumer-miss",
    title: "Consumer Spending Misses Estimate",
    description: "Retail names reprice down as demand weakens.",
    visibility: "public",
    affectedSectors: ["retail"],
    direction: -0.75,
    magnitude: 0.8,
    confidence: 0.8,
    tags: ["consumer", "macro"],
    macroWeights: { "Consumer Slowdown": 1.4 }
  },
  {
    id: "exchange-outage",
    title: "Exchange Outage Freezes Crypto Liquidity",
    description: "Execution bottlenecks widen spreads in crypto-like assets.",
    visibility: "public",
    affectedSectors: ["crypto"],
    direction: -0.65,
    magnitude: 0.9,
    confidence: 0.7,
    heatImpact: 2,
    tags: ["liquidity", "crypto"],
    macroWeights: { "Liquidity Squeeze": 1.5 }
  },
  {
    id: "reg-sector-scrutiny",
    title: "Regulator Hints at Sector Scrutiny",
    description: "A surprise hearing raises enforcement odds.",
    visibility: "public",
    affectedSectors: ["tech", "crypto"],
    direction: -0.45,
    magnitude: 0.6,
    confidence: 0.8,
    heatImpact: 8,
    tags: ["legal", "regulator"]
  },
  {
    id: "mega-contract-tech",
    title: "Mega Contract Awarded to Tech Supplier",
    description: "Large procurement win lifts growth expectations.",
    visibility: "public",
    affectedSectors: ["tech"],
    direction: 0.6,
    magnitude: 0.65,
    confidence: 0.72,
    tags: ["tech", "event"],
    macroWeights: { "Risk-On": 1.2, "AI Hype": 1.2 }
  },
  {
    id: "short-report",
    title: "Short Report Circulates",
    description: "A high-profile short thesis pressures sentiment.",
    visibility: "public",
    affectedSectors: ["tech", "retail", "crypto"],
    direction: -0.55,
    magnitude: 0.58,
    confidence: 0.65,
    heatImpact: 3,
    tags: ["rumor", "sentiment"]
  },
  {
    id: "analyst-upgrade-wave",
    title: "Analyst Upgrade Wave",
    description: "Sell-side revisions drive broad repricing higher.",
    visibility: "research",
    affectedSectors: ["tech", "energy", "retail"],
    direction: 0.5,
    magnitude: 0.55,
    confidence: 0.66,
    tags: ["research", "sentiment"]
  },
  {
    id: "pipeline-delay",
    title: "Pipeline Delay Confirmed",
    description: "Lead compound delay dents pharma near-term outlook.",
    visibility: "public",
    affectedSectors: ["pharma"],
    direction: -0.6,
    magnitude: 0.66,
    confidence: 0.83,
    tags: ["pharma", "event"]
  },
  {
    id: "commodity-surge",
    title: "Commodity Basket Surges",
    description: "Input prices jump and rotate flows into energy.",
    visibility: "public",
    affectedSectors: ["energy", "retail"],
    direction: 0.45,
    magnitude: 0.52,
    confidence: 0.75,
    tags: ["commodity", "macro"],
    macroWeights: { "Inflation Scare": 1.4 }
  },
  {
    id: "buyback-authorization",
    title: "Aggressive Buyback Authorization",
    description: "Capital return update supports selected shares.",
    visibility: "research",
    affectedSectors: ["tech", "retail"],
    direction: 0.4,
    magnitude: 0.48,
    confidence: 0.7,
    tags: ["capital", "research"]
  },
  {
    id: "whistleblower-filing",
    title: "Whistleblower Filing Emerges",
    description: "Internal allegations trigger compliance concerns.",
    visibility: "public",
    affectedSectors: ["pharma", "tech"],
    direction: -0.62,
    magnitude: 0.63,
    confidence: 0.79,
    heatImpact: 6,
    tags: ["legal", "scandal"]
  },
  {
    id: "liquidity-backstop",
    title: "Liquidity Backstop Announced",
    description: "Funding stress eases across risk assets.",
    visibility: "public",
    affectedSectors: ["tech", "crypto", "retail"],
    direction: 0.56,
    magnitude: 0.6,
    confidence: 0.74,
    tags: ["liquidity", "macro"],
    macroWeights: { "Liquidity Squeeze": 1.5 }
  },
  {
    id: "rate-cut-gossip",
    title: "Emergency Rate-Cut Gossip",
    description: "Speculation fuels a risk-on chase.",
    visibility: "questionable",
    affectedSectors: ["tech", "crypto", "retail"],
    direction: 0.7,
    magnitude: 0.78,
    confidence: 0.4,
    heatImpact: 3,
    tags: ["rumor", "macro"]
  },
  {
    id: "bond-demand-surge",
    title: "Safety Bid Lifts Bond Desk",
    description: "Flight-to-quality supports defensive carry.",
    visibility: "public",
    affectedSectors: ["bonds"],
    direction: 0.45,
    magnitude: 0.4,
    confidence: 0.88,
    tags: ["defensive", "macro"],
    macroWeights: { "Risk-Off": 1.3 }
  },
  {
    id: "crypto-bridge-hack",
    title: "Bridge Exploit Hits Digital Venues",
    description: "Security shock triggers abrupt de-risking.",
    visibility: "public",
    affectedSectors: ["crypto"],
    direction: -0.78,
    magnitude: 0.9,
    confidence: 0.82,
    heatImpact: 5,
    tags: ["crypto", "security"]
  },
  {
    id: "energy-subsidy",
    title: "Energy Subsidy Package Floated",
    description: "Fiscal plan aids grid operators and refiners.",
    visibility: "research",
    affectedSectors: ["energy"],
    direction: 0.5,
    magnitude: 0.56,
    confidence: 0.67,
    tags: ["policy", "energy"]
  },
  {
    id: "retail-margin-warning",
    title: "Retail Margin Warning",
    description: "Guidance cut raises concerns around discounting.",
    visibility: "public",
    affectedSectors: ["retail"],
    direction: -0.58,
    magnitude: 0.6,
    confidence: 0.84,
    tags: ["consumer", "earnings"]
  },
  {
    id: "ai-chip-breakthrough",
    title: "AI Accelerator Breakthrough",
    description: "Productivity narrative reignites growth appetite.",
    visibility: "public",
    affectedSectors: ["tech", "crypto"],
    direction: 0.62,
    magnitude: 0.69,
    confidence: 0.69,
    tags: ["ai", "sentiment"],
    macroWeights: { "AI Hype": 1.6 }
  },
  {
    id: "compliance-sweep",
    title: "Regulator Launches Compliance Sweep",
    description: "Cross-sector audit chatter raises scrutiny.",
    visibility: "public",
    affectedSectors: ["tech", "pharma", "crypto"],
    direction: -0.35,
    magnitude: 0.42,
    confidence: 0.9,
    heatImpact: 10,
    tags: ["regulator", "compliance"]
  }
];
